name: caller

on:
  push:
    branches:
    - '*'

  pull_request:
    branches:
    - '*'
  workflow_call:

jobs:
  build:
    uses: ./.github/workflows/called.yml
  post-build:
    needs: build
    runs-on: ubuntu-latest
    # if: a-b-c-d.steps["setup python"].outputs.triggered == 'true'
    # if: needs.build.outputs.out1 == 'true'
    steps:
      - env:
          OUTPUT1: ${{needs.build.outputs}}
        run: echo "$OUTPUT1"
      # - uses: actions/checkout@v2
      # - uses: actions/setup-python@v4
      #   name: setup python 3.9
      #   with:
      #     python-version: '3.9' 