name: a-b-c-d

on:
  push:
    branches:
    - '*'

  pull_request:
    branches:
    - '*'
  workflow_call:
    outputs:
      outA:
        value: ${{ jobs.build.steps.step1.triggered }}

jobs:
  build:
    runs-on: ubuntu-latest
    # outputs:
    #   out1: steps["setup python"].outputs.triggered
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        name: setup python
        id: step1
        with:
          python-version: '3.8' 
      # - id: step2
      #   run: echo "::set-output name=step2out::true"
