name: carsus-tests

on:
  push:
    branches:
    - '*'

  pull_request:
    branches:
    - '*'

jobs:
  nist-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        name: python
        with:
          python-version: '3.8' 

      - name: install requests
        run: pip install requests
      
      - name: Download Nist Data
        run: |
          python -c """
          import requests
          WEIGHTSCOMP_URL = 'http://physics.nist.gov/cgi-bin/Compositions/stand_alone.pl'
          res = requests.get(WEIGHTSCOMP_URL, params={'ascii': 'ascii2', 'isotype': 'some'})
          """
