name: carsus-atomic-file-search

# on:
#   push:
#   schedule:
#     # Run every hour
#     - cron: 0 * * * *

# on: 
#   workflow_dispatch

on:
  push:
    branches:
    - '*'

  pull_request:
    branches:
    - '*'



jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
        # with:
        #   repository: tardis-sn/carsus
        #   # ref: # TODO
        #   path: carsus_latest/
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8' 

      - name: get new certificate
        run: echo | openssl s_client -connect physics.nist.gov:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > certificate.crt

      - name: cat certificate
        run: cat certificate.crt

      - name: get certifi
        run: pip install certifi

      - name: Update certificates
        run: |
          python -c """
          import certifi
          print(certifi.where())
          with open(certifi.where(), 'a') as f1, open('certificate.crt', 'r') as  f2:
            print(f1.read())
            f1.write(f2.read())
            print(f1.read())
          """

      - name: create file
        run: touch test_file
      - name: try printing hostname
        run: echo ${{ secrets.GH_DROPOFF_USERNAME }}

      # - name: SCP
      #   run: scp scp test_file ghci@moria.egr.msu.edu:/storage/github_dropoffs/tardis/ 
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.GH_DROPOFF_HOST }}
          username: ${{ secrets.GH_DROPOFF_USERNAME }}
          password: ${{ secrets.GH_DROPOFF_PASSWORD }}
          source: '*_*'
          target: "/storage/github_dropoffs/tardis/"

          
        
      
        
          