name: carsus-atomic-file-search

# on:
#   push:
#   schedule:
#     # Run every hour
#     - cron: 0 * * * *

# on: 
#   workflow_dispatch

on:
  push:
    branches:
    - '*'

  pull_request:
    branches:
    - '*'



jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # with:
        #   repository: tardis-sn/carsus
        #   # ref: # TODO
        #   path: carsus_latest/

      - name: create file
        run: touch test_file

      # - name: SCP
      #   run: scp scp test_file ghci@moria.egr.msu.edu:/storage/github_dropoffs/tardis/ 
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "*_*"
          target: "/storage/github_dropoffs/tardis/"

          
        
      
        
          