name: carsus-atomic-file-search

# on:
#   push:
#   schedule:
#     # Run every hour
#     - cron: 0 * * * *

on: 
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)    
        required: false

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: tardis-sn/carsus
          # ref: # TODO
          path: carsus_latest/
          
        
      
        
          